name: MainWorkflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello from Octo Organization
  build2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a harmless script
        run: echo I also passed
  build3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a harmless script
        run: exit 1
